"""agrego columna ingredients a la tabla  tragos

Revision ID: 6dab6c167e83
Revises: db9269b93d66
Create Date: 2024-11-24 16:28:58.366837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dab6c167e83'
down_revision: Union[str, None] = 'db9269b93d66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tragos', sa.Column('ingredients', sa.String(length=2000), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tragos', 'ingredients')
    # ### end Alembic commands ###
